default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: saviour
  password: 12345
  host: localhost
  port: 5432

development:
  <<: *default
  database: Backend_development_development

test:
  <<: *default
  database: Backend_development_test

production:
  <<: *default
  database: Backend_development_production
