# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: saviour
  password: 12345

development:
  <<: *default
  database: Backend

test:
  <<: *default
  database: Backend_test

production:
  <<: *default
  database: Backend_production
  username: Backend
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
